spring.application.name=api-gateway
server.port=8080

# Product Service
spring.cloud.gateway.routes[0].id=products-service
spring.cloud.gateway.routes[0].uri=http://localhost:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/products/**

# Orders Service
spring.cloud.gateway.routes[1].id=orders-service
spring.cloud.gateway.routes[1].uri=http://localhost:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/orders/**
spring.cloud.gateway.routes[1].filters[0]=StripPrefix=0
